server:
  port: 7001

netty:
  server:
    name: server
    port: 6001


spring:
  application:
    name: server
  redis:
    host: localhost
    port: 6379
    #password: ee
    database: 1
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 500
      min-idle: 0
    timeout: 0


monitor:
  #type: redis
  type: http
  url: http://localhost:7002/postmsg
  mail:
    enable:
      ssl: false
    host: smtp.163.com
    password: yourpassword
    username: miles02
    from: miles02@163.com
    to: 124746406@qq.com
    cc: 88943553@qq.com  #抄送
    bcc: 88943553@qq.com  #密送